# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# lets put some templates
Template.destroy_all

Template.create({title: "Staubsauger", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Abstellkammer"})
Template.create({title: "Dampfreiniger", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Abstellkammer"})
Template.create({title: "Bügeleisen", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Abstellkammer"})
Template.create({title: "Wäschemangel", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Abstellkammer"})
Template.create({title: "Robotersauger", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Abstellkammer"})
Template.create({title: "Einfache Reinigungsmittel", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Abstellkammer"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Abstellkammer"})

Template.create({title: "Zelt", details_hint: "", rate_eur: 20.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Isomatte (aufblasbar)", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Campingkocher", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Wanderrucksack", details_hint: "Größe", rate_eur: 10.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Camping Laterne", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Hängematte", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Camping"})
Template.create({title: "Schlafsack", details_hint: "Größe", rate_eur: 5.0, rate_interval: "week", room: "Camping"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Camping"})

Template.create({title: "Smoothie Mixer", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Fondueset", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Raclette", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Brotbackautomat", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Küche"})
Template.create({title: "Küchenmaschine", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Fritteuse", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Waffeleisen", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Entsafter", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Sandwichtoaster", details_hint: "", rate_eur: 2.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Dampfgarer", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Dörrautomat", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Küche"})
Template.create({title: "Einfache Küchenutensilien", details_hint: "Töpfe, Pfannen, Sieb, Teigrolle u.ä.", rate_eur: 1.0, rate_interval: "day", room: "Küche"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Küche"})

Template.create({title: "Bierbankgarnitur", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Rasenmäher", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Gartenhäcksler", details_hint: "", rate_eur: 10.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Grill", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Gartenpavillon", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Slagline", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Minitrampolin", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Trampolin", details_hint: "", rate_eur: 10.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Pool", details_hint: "", rate_eur: 10.0, rate_interval: "day", room: "Garten"})
Template.create({title: "Heckenschneider", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Garten"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Garten"})

Template.create({title: "Surfbrett", details_hint: "", rate_eur: 25.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Snowboard", details_hint: "", rate_eur: 25.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Neoprenanzug", details_hint: "Größe", rate_eur: 10.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Flossen", details_hint: "Größe", rate_eur: 5.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Tauchmaske", details_hint: "", rate_eur: 5.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Fahrrad", details_hint: "Typ", rate_eur: 5.0, rate_interval: "day", room: "Sport"})
Template.create({title: "Slagline", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Sport"})
Template.create({title: "Inline Skates", details_hint: "Größe", rate_eur: 3.0, rate_interval: "day", room: "Sport"})
Template.create({title: "Stand-Up Paddleboard", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Sport"})
Template.create({title: "Ski", details_hint: "Typ und Größe", rate_eur: 25.0, rate_interval: "week", room: "Sport"})
Template.create({title: "Schlauchboot", details_hint: "Größe", rate_eur: 5.0, rate_interval: "day", room: "Sport"})
Template.create({title: "Paddelboot", details_hint: "Größe", rate_eur: 10.0, rate_interval: "day", room: "Sport"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Sport"})

Template.create({title: "Trommel", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Musikinstrumente"})
Template.create({title: "Gitarre", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Musikinstrumente"})
Template.create({title: "E-Piano", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Musikinstrumente"})
Template.create({title: "Geige", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Musikinstrumente"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Musikinstrumente"})

Template.create({title: "Drucker", details_hint: "", rate_eur: 0.10, rate_interval: "page", room: "Büro"})
Template.create({title: "Scanner", details_hint: "", rate_eur: 0.10, rate_interval: "scan", room: "Büro"})
Template.create({title: "Beamer", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Büro"})
Template.create({title: "Schredder", details_hint: "", rate_eur: 2.0, rate_interval: "day", room: "Büro"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Büro"})

Template.create({title: "Anzug", details_hint: "Größe", rate_eur: 10.0, rate_interval: "day", room: "Kleidung Männer"})
Template.create({title: "Frack", details_hint: "Größe", rate_eur: 10.0, rate_interval: "day", room: "Kleidung Männer"})
Template.create({title: "Faschingskostüm", details_hint: "Größe und Typ", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Männer"})
Template.create({title: "Halloweenkostüm", details_hint: "Größe und Typ", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Männer"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Kleidung Männer"})

Template.create({title: "Abendkleid", details_hint: "Größe", rate_eur: 10.0, rate_interval: "day", room: "Kleidung Frauen"})
Template.create({title: "Kostüm", details_hint: "Größe", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Frauen"})
Template.create({title: "Hosenanzug", details_hint: "Größe", rate_eur: 10.0, rate_interval: "day", room: "Kleidung Frauen"})
Template.create({title: "Faschingskostüm", details_hint: "Größe und Typ", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Frauen"})
Template.create({title: "Halloweenkostüm", details_hint: "Größe und Typ", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Frauen"})
Template.create({title: "Sporttrickot", details_hint: "Größe und Typ", rate_eur: 5.0, rate_interval: "day", room: "Kleidung Frauen"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Kleidung Frauen"})

Template.create({title: "Bohrmaschine", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Schleifmaschine", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Drehmomentschlüssel", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Akkuschrauber", details_hint: "", rate_eur: 3.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Einfache Werkzeuge", details_hint: "Schrauberzieher, Hammer, Schraubenschlüssel u.ä.", rate_eur: 1.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Winkelschleifer", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Dremel", details_hint: "", rate_eur: 5.0, rate_interval: "day", room: "Werkstatt"})
Template.create({title: "Standbohrmaschine", details_hint: "", rate_eur: 5.0, rate_interval: "use", room: "Werkstatt"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: "Werkstatt"})
#Template.create({title: "", details_hint: "", rate_eur: 1.0, rate_interval: "day", room: ""})
